const PropertyArray = [
  {
    code: "MPM12345",
    fullAddress: "61 Lakeside Road, Frankton, Hamilton",
    region: "Hamilton",
    suburb: "Frankton",
    price: "494",
    specialText: "Close to City Center",
    bedroom: 3,
    bathroom: 1,
    parking: 2,
    numberOfTenants: 6,
    petFriendly: true,
    availability: false,
    furnished: true,
    images: [
      "property1/one.png",
      "property1/two.png",
      "property1/three.png",
      "property1/four.png",
      "property1/five.png",
    ],
  },
  {
    code: "MPM12342",
    fullAddress: "61 Manukau Road, Manukau, Auckland",
    region: "Auckland",
    suburb: "Manukau",
    price: "500",
    specialText: "Close to Shopping centre",
    bedroom: 4,
    bathroom: 2,
    parking: 3,
    numberOfTenants: 8,
    petFriendly: true,
    availability: true,
    furnished: false,
    images: [
      "property2/one.png",
      "property2/two.png",
      "property2/three.png",
      "property2/four.png",
      "property2/five.png",
    ],
  },
  {
    code: "MPM12340",
    fullAddress: "30 Takanini School Road, Takanini, Auckland",
    region: "Auckland",
    suburb: "Papakura",
    price: "600",
    specialText: "Close to Shopping centre",
    bedroom: 5,
    bathroom: 3,
    parking: 4,
    numberOfTenants: 9,
    petFriendly: true,
    availability: true,
    furnished: false,
    images: [
      "property3/one.png",
      "property3/two.png",
      "property3/three.png",
      "property3/four.png",
      "property3/five.png",
    ],
  },
  {
    code: "MPM12320",
    fullAddress: "12 Briston Drive, Pinehill",
    region: "Auckland",
    suburb: "Northcote",
    price: "450",
    specialText: "New Build in a Quiet Location",
    bedroom: 2,
    bathroom: 1,
    parking: 0,
    numberOfTenants: 4,
    petFriendly: false,
    availability: false,
    furnished: true,
    images: [
      "property4/one.png",
      "property4/two.png",
      "property4/three.png",
      "property4/four.png",
      "property4/five.png",
    ],
  },
  {
    code: "MPM12330",
    fullAddress: "172 Cornwell Road, Albany",
    region: "Auckland",
    suburb: "Albany",
    price: "500",
    specialText: "Renovated Rustic Build",
    bedroom: 6,
    bathroom: 2,
    parking: 1,
    numberOfTenants: 7,
    petFriendly: false,
    availability: true,
    furnished: true,
    images: [
      "property5/one.png",
      "property5/two.png",
      "property5/three.png",
      "property5/four.png",
      "property5/five.png",
    ],
  },
];

export default PropertyArray;
